# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nittutorial', '0021_auto_20160416_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=models.TextField(),
        ),
    ]
