# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nittutorial', '0022_auto_20160418_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='authorId',
            field=models.IntegerField(default=123),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
